name = "ecofiberbdv2"
main = "src/index.js"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[build]
command = "npm run build"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "ecofiberbd"
database_id = "ecofiberbd"
